let eng = [
  "Yes",
  "no",
  "are",
  "is",
  "the",
  "it",
  "and",
  "What",
  "will",
  "in",
  "for",
  "that",
  "you",
  "that",
  "by",
  "with",
  "Mi",
  "You are",
  "her",
  "How",
  "I",
  "GI",
  "This",
  "am",
  "well",
  "me",
  "you",
  "Only",
  "Lee",
  "No",
  "But",
  "if",
  "a",
  "he",
  "was",
  "should",
  "When",
  "now",
  "a lot",
  "I know",
  "Who",
  "His",
  "There are",
  "something",
  "can",
  "me",
  "would",
  "where",
  "I want",
  "you",
  "Here",
  "Did",
  "like that",
  "Why",
  "all",
  "Come on",
  "order",
  "NO",
  "so",
  "you know",
  "Here",
  "She",
  "I can",
  "be",
  "After",
  "I think",
  "want",
  "to",
  "one",
  "you",
  "still",
  "or",
  "someone",
  "But",
  "time",
  "nothing",
  "They",
  "there",
  "We are",
  "must",
  "are",
  "before",
  "maybe",
  "I have",
  "you",
  "a little",
  "please",
  "We",
  "hey",
  "more",
  "We are going",
  "Really",
  "can",
  "how much",
  "him",
  "mine",
  "work",
  "Then",
  "Go",
  "hi",
  "So much",
  "never",
  "you have",
  "people",
  "you",
  "You mean",
  "Im",
  "who",
  "So",
  "That is why",
  "one",
  "thank you",
  "my",
  "This one",
  "which",
  "father",
  "already",
  "works",
  "right",
  "without",
  "I am going",
  "tell",
  "man",
  "We have",
  "years",
  "us",
  "day",
  "This",
  "Thanks",
  "you do",
  "at",
  "wants",
  "do",
  "o",
  "said",
  "see",
  "yours",
  "I was",
  "seems",
  "while",
  "because",
  "happen",
  "Say",
  "way",
  "you",
  "yours",
  "nobody",
  "thought",
  "place",
  "these",
  "at home",
  "mother",
  "always",
  "sadness",
  "I must",
  "be",
  "her",
  "good",
  "Bill",
  "come",
  "better",
  "God",
  "Wait",
  "them",
  "going on",
  "a few",
  "be you",
  "We can",
  "the people",
  "any",
  "immediately",
  "life",
  "that",
  "woman",
  "Sure",
  "Dad",
  "Mister",
  "Everyone",
  "good",
  "knows",
  "the same",
  "right",
  "mine",
  "sorry",
  "I see",
  "Here",
  "surely",
  "oh",
  "money",
  "I said",
  "because of",
  "give",
  "said",
  "You go",
  "doing",
  "return",
  "Say",
  "Do not",
  "still",
  "Even",
  "should have",
  "I do",
  "I wanted",
  "again",
  "see",
  "You see",
  "come",
  "after",
  "some",
  "another",
  "enough",
  "out",
  "You know",
  "three",
  "help",
  "mine",
  "Just",
  "one",
  "ok",
  "nice",
  "Listen",
  "toward",
  "shit",
  "You want",
  "Life",
  "problem",
  "again",
  "great",
  "I do not have",
  "yours",
  "Today",
  "mine",
  "brother",
  "had",
  "son",
  "Mr.",
  "two",
  "sorry",
  "under",
  "the devils",
  "way",
  "TRUE",
  "Name",
  "together",
  "part",
  "two",
  "Too much",
  "Then",
  "guys",
  "Is it",
  "minutes",
  "Jack",
  "you have",
  "sure",
  "You are talking",
  "Let it",
  "through",
  "You have to",
  "connection",
  "tomorrow",
  "do",
  "We see",
  "why",
  "friend",
  "Like",
  "night",
  "We have to",
  "kid",
  "I saw",
  "our",
  "children",
  "back",
  "actually",
  "around",
  "ours",
  "bad",
  "girl",
  "Mom",
  "boy",
  "the world",
  "which",
  "I understand",
  "were",
  "fast",
  "I believe",
  "I knew",
  "mine",
  "your",
  "ours",
  "inside",
  "wanted",
  "Dead",
  "Sweetheart",
  "his",
  "yourself",
  "you do",
  "side",
  "work",
  "You can",
  "Leave",
  "except",
  "Tonight",
  "sometimes",
  "have",
  "alone",
  "It was supposed",
  "yours",
  "yours",
  "else",
  "We know",
  "once",
  "year",
  "some",
  "I get back",
  "whom",
  "enough",
  "Look",
  "important",
  "long",
  "He wanted",
  "friends",
  "large",
  "comes",
  "talking",
  "Call",
  "glad",
  "Mr.",
  "help",
  "great",
  "be",
  "hard",
  "against",
  "love",
  "We are doing",
  "take",
  "give",
  "his",
  "We find",
  "house",
  "can",
  "Purpose",
  "through",
  "big",
  "John",
  "We are",
  "days",
  "We do",
  "Mr.",
  "first",
  "course",
  "before",
  "Stop",
  "Hope",
  "I find",
  "finish",
  "the money",
  "what kind",
  "nor",
  "worries",
  "others",
  "moment",
  "two",
  "I take",
  "Simple",
  "but",
  "things",
  "found",
  "like this",
  "case",
  "happened",
  "Lucky",
  "What",
  "evening",
  "the house",
  "There is",
  "was",
  "both of them",
  "at least",
  "says",
  "the city",
  "type",
  "let go",
  "God",
  "man",
  "shout",
  "I said",
  "Thoughts",
  "will",
  "See",
  "However",
  "family",
  "tell",
  "I had",
  "He saw",
  "the car",
  "Yes",
  "no",
  "are",
  "is",
  "the",
  "it",
  "and",
  "What",
  "will",
  "in",
  "for",
  "that",
  "you",
  "that",
  "by",
  "with",
  "Mi",
  "You are",
  "her",
  "How",
  "I",
  "GI",
  "This",
  "am",
  "well",
  "me",
  "you",
  "Only",
  "Lee",
  "No",
  "But",
  "if",
  "a",
  "he",
  "was",
  "should",
  "When",
  "now",
  "a lot",
  "I know",
  "Who",
  "His",
  "There are",
  "something",
  "can",
  "me",
  "would",
  "where",
  "I want",
  "you",
  "Here",
  "Did",
  "like that",
  "Why",
  "all",
  "Come on",
  "order",
  "NO",
  "so",
  "you know",
  "Here",
  "She",
  "I can",
  "be",
  "After",
  "I think",
  "want",
  "to",
  "one",
  "you",
  "still",
  "or",
  "someone",
  "But",
  "time",
  "nothing",
  "They",
  "there",
  "We are",
  "must",
  "are",
  "before",
  "maybe",
  "I have",
  "you",
  "a little",
  "please",
  "We",
  "hey",
  "more",
  "We are going",
  "Really",
  "can",
  "how much",
  "him",
  "mine",
  "work",
  "Then",
  "Go",
  "hi",
  "So much",
  "never",
  "you have",
  "people",
  "you look",
];

let mk = [
  "Да",
  "Не",
  "се",
  "е",
  "на",
  "тоа",
  "и",
  "Што",
  "волја",
  "во",
  "за",
  "тоа",
  "ти",
  "тоа",
  "од",
  "со",
  "Ми",
  "Ти си",
  "Нејзината",
  "Како",
  "Јас",
  "Gi",
  "Ова",
  "сум",
  "Па",
  "Јас",
  "ти",
  "Само",
  "Ли",
  "Не",
  "Но",
  "Ако",
  "а",
  "тој",
  "беше",
  "треба",
  "Кога",
  "Сега",
  "многу",
  "Знам",
  "СЗО",
  "Неговиот",
  "Има",
  "нешто",
  "може",
  "Јас",
  "би",
  "каде",
  "сакам",
  "ти",
  "Еве",
  "Правеше",
  "како тоа",
  "Зошто",
  "сите",
  "Ајде",
  "со цел",
  "Не",
  "Значи",
  "знаеш",
  "Еве",
  "Таа",
  "јас можам",
  "биди",
  "По",
  "јас мислам",
  "сака",
  "до",
  "Еден",
  "ти",
  "Сепак",
  "или",
  "некој",
  "Но",
  "време",
  "ништо",
  "Тие",
  "Таму",
  "Ние сме",
  "мора",
  "се",
  "пред",
  "можеби",
  "имам",
  "ти",
  "малку",
  "те молам",
  "Ние",
  "Еј",
  "повеќе",
  "Одеа",
  "Навистина",
  "може",
  "колку",
  "него",
  "мој",
  "работа",
  "Потоа",
  "Оди",
  "здраво",
  "Многу",
  "Никогаш",
  "имаш",
  "луѓе",
  "ти",
  "Мислиш",
  "Јас сум",
  "СЗО",
  "Значи",
  "Затоа",
  "Еден",
  "Ви благодарам",
  "Мојот",
  "Оваа",
  "кои",
  "Татко",
  "Веќе",
  "Работи",
  "десно",
  "без",
  "Одам",
  "Кажи",
  "Човек",
  "Ние имаме",
  "години",
  "нас",
  "ден",
  "Ова",
  "Благодарам",
  "ти правиш",
  "на",
  "сака",
  "направи",
  "О",
  "кажа",
  "Погледнете",
  "твое",
  "јас бев",
  "се чини",
  "додека",
  "затоа што",
  "се случи",
  "Рече",
  "начин",
  "ти",
  "твое",
  "Никој",
  "мисла",
  "место",
  "овие",
  "Дома",
  "Мајка",
  "Секогаш",
  "тага",
  "Јас морам",
  "биди",
  "Нејзината",
  "добро",
  "Бил",
  "Дојди",
  "подобро",
  "Бог",
  "Почекај",
  "нив",
  "продолжува",
  "неколку",
  "Биди ти",
  "Ние можеме",
  "луѓето",
  "било што",
  "веднаш",
  "Lifeивотот",
  "тоа",
  "жена",
  "Сигурно",
  "Тато",
  "Господине",
  "Сите",
  "добро",
  "знае",
  "исто",
  "десно",
  "мој",
  "Извини",
  "гледам",
  "Еве",
  "Сигурно",
  "Ох",
  "пари",
  "реков",
  "поради",
  "дај",
  "кажа",
  "Ти оди",
  "правење",
  "Врати се",
  "Рече",
  "Не",
  "Сепак",
  "Дури и",
  "би требало да има",
  "да",
  "јас сакав",
  "повторно",
  "Погледнете",
  "Ти гледаш",
  "Дојди",
  "по",
  "некои",
  "друг",
  "доволно",
  "надвор",
  "Знаеш",
  "три",
  "помош",
  "мој",
  "Само",
  "Еден",
  "добро",
  "убаво",
  "Слушајте",
  "кон",
  "срање",
  "Ти сакаш",
  "Lifeивотот",
  "проблем",
  "повторно",
  "Одлично",
  "немам",
  "твое",
  "Денес",
  "мој",
  "брат",
  "имаше",
  "син",
  "Г.",
  "Две",
  "Извини",
  "под",
  "Devаволите",
  "начин",
  "Точно",
  "Име",
  "Заедно",
  "дел",
  "Две",
  "Премногу",
  "Потоа",
  "момчиња",
  "Дали е тоа",
  "минути",
  "Jackек",
  "имаш",
  "сигурно",
  "Зборуваш",
  "Нека",
  "преку",
  "Мора да",
  "врска",
  "Утре",
  "направи",
  "Ние гледаме",
  "Зошто",
  "Пријател",
  "Допаѓа",
  "ноќ",
  "Ние мораме",
  "дете",
  "јас видов",
  "Нашиот",
  "деца",
  "назад",
  "всушност",
  "Околу",
  "наши",
  "лошо",
  "девојче",
  "Мајка",
  "Момче",
  "светот",
  "кои",
  "разбирам",
  "беа",
  "Брзо",
  "јас верувам",
  "знаев",
  "мој",
  "Твое",
  "наши",
  "Внатре",
  "сакаше",
  "Мртво",
  "Душо",
  "Неговиот",
  "сами",
  "ти правиш",
  "страна",
  "работа",
  "Ти можеш",
  "Остави",
  "освен",
  "Вечерва",
  "понекогаш",
  "имаат",
  "сам",
  "Тоа беше претпоставено",
  "твое",
  "твое",
  "друго",
  "Знаеме",
  "Еднаш",
  "година",
  "некои",
  "Се враќам",
  "кого",
  "доволно",
  "Погледнете",
  "важно",
  "Долго",
  "Тој сакаше",
  "пријатели",
  "Голем",
  "доаѓа",
  "Зборувајќи",
  "Повик",
  "Мило ми е",
  "Г.",
  "помош",
  "Одлично",
  "биди",
  "тешко",
  "Против",
  "Loveубов",
  "Ние правиме",
  "Земете",
  "дај",
  "Неговиот",
  "Ние најдовме",
  "куќа",
  "може",
  "Цел",
  "преку",
  "големо",
  "Јован",
  "Ние сме",
  "денови",
  "Ние правиме",
  "Г.",
  "Прво",
  "курс",
  "пред",
  "Стоп",
  "Надеж",
  "јас наоѓам",
  "Заврши",
  "пари",
  "каков вид",
  "Ниту",
  "грижи",
  "други",
  "момент",
  "Две",
  "јас земам",
  "Едноставно",
  "Но",
  "работи",
  "Пронајден",
  "како ова",
  "случај",
  "се случи",
  "Среќа",
  "Што",
  "вечер",
  "куќата",
  "Ете го",
  "беше",
  "двајцата",
  "барем",
  "вели",
  "градот",
  "тип",
  "Остави",
  "Бог",
  "Човек",
  "викање",
  "реков",
  "Мисли",
  "волја",
  "Погледнете",
  "Сепак",
  "семејство",
  "Кажи",
  "имав",
  "Тој виде",
  "Колата",
  "Да",
  "Не",
  "се",
  "е",
  "на",
  "тоа",
  "и",
  "Што",
  "волја",
  "во",
  "за",
  "тоа",
  "ти",
  "тоа",
  "од",
  "со",
  "Ми",
  "Ти си",
  "Нејзината",
  "Како",
  "Јас",
  "Gi",
  "Ова",
  "сум",
  "Па",
  "Јас",
  "ти",
  "Само",
  "Ли",
  "Не",
  "Но",
  "Ако",
  "а",
  "тој",
  "беше",
  "треба",
  "Кога",
  "Сега",
  "многу",
  "Знам",
  "СЗО",
  "Неговиот",
  "Има",
  "нешто",
  "може",
  "Јас",
  "би",
  "каде",
  "сакам",
  "ти",
  "Еве",
  "Правеше",
  "како тоа",
  "Зошто",
  "сите",
  "Ајде",
  "со цел",
  "Не",
  "Значи",
  "знаеш",
  "Еве",
  "Таа",
  "јас можам",
  "биди",
  "По",
  "јас мислам",
  "сака",
  "до",
  "Еден",
  "ти",
  "Сепак",
  "или",
  "некој",
  "Но",
  "време",
  "ништо",
  "Тие",
  "Таму",
  "Ние сме",
  "мора",
  "се",
  "пред",
  "можеби",
  "имам",
  "ти",
  "малку",
  "те молам",
  "Ние",
  "Еј",
  "повеќе",
  "Одеа",
  "Навистина",
  "може",
  "колку",
  "него",
  "мој",
  "работа",
  "Потоа",
  "Оди",
  "здраво",
  "Многу",
  "Никогаш",
  "имаш",
  "луѓе",
  "изгледаш",
];
htmlQuestions = [
  "Sto e kratenkta HTML",
  "Sto e kratnkata https",
  "Sto znaci url",
  "Od koi delovi se sostoi najcesto html-elementot",
  "Dali site html-elementi imaat kraen tag",
  "Nabroj tri elementi sto nemaat kraen end tag",
  "Sto e atribut",
  "Kade se stava atributot",
  "Nabroj nekolku atributi na html elementi",
  "Koj element e najmal heading",
  "Koj html element stava linija",
  "Koj html element se koristi za premin na nova linija",
  "koja e sintaksata na atribut",
  "koj element se koristi za hiperlink",
  "Koj atribut se stava vo link html element ",
  "Koj html element se korisi za stavanje na slika image",
  "Dali <img> tagot ima closing tag",
  "Koi atributi treba da se stavat vo <img> tag",
  "Koja vrednost value treba da se stavi vo src atribut na <img> tag",
  "Sto se pisuva vo alt atribut na <img> tag",
  "Koj element se koristi za paragraf",
  "Koj atribut se stava za da se selektiraat poveke elementi po vrednosta na toj atribut",
  "Koj atribut se stava za da se identifikuva nekoj element",
  "Sto se blok elementi vo html",
  "Nabroj nekolku blok element",
  "Sto se inline elementi vo html",
  "Nabroj nekoi inline elementi",
  "Kaja aplikacija treba da imame za da otvorime-izvrsime html-file",
  "Kade vo html-file se pisuvaat informacii za taa veb strana",
  "Koi tagovi ja pravat osnovnata struktura na veb strana",
  "Vo koj tag se kodira toa sto go gledame na veb stranata",
  "Vo koj atribut se stilizira toj element",
  "Vo koj tag se stiliziraat html elementi",
  "Koj html element se koristi za javascript skripta",
  "Koj html element se koristi za stavanje na navodnici",
  "Kako se stavaat komentari vo html",
  "Kako se stavaat boi",
  "Kako se pravi podredena lista vo html",
  "Kako se pravi nepodredena lista vo html",
  "Koj tag se koristi za grupiranje na html elementi",
];
htmlAnswers = [
  "hypertext markaup language",
  "Hypertext transfer protocol secure",
  "Uniform resource locator",
  "Poceten tag, content, kraen tag",
  "Ne",
  "<img>,<hr>,<br> ",
  "Dopolnitelna informacija za tagot",
  "Atributot se stava vo poceten tag",
  "id,class,style, href, src,alt, target ",
  "<h6>",
  "<hr>",
  "<br>",
  "name='value'",
  "<a>",
  "href",
  "<img>",
  "Ne",
  "src, alt, width, height",
  "url na slika",
  "text sto ja opisuva slikata",
  "p",
  "class",
  "id",
  "Zapocnuvaat vo nov red i se prostiraat do kraj na sirinata parent elementot",
  "<p>,<h1-h6> ,<ol>, <ul>, <li>, <br>, <hr>",
  "Ne zapocnuvaat vo nov red i zazemaat sirina kolku sto imaat sodrzina content",
  "<a>,<span>,<img>,<strong>,<em>,<sub>,<sup>",
  "browser,prebaruvac",
  "vo <head>",
  "<html><head></head><body></body></html>",
  "<body>",
  "style",
  "<style>",
  "<script>",
  "<q>",
  "<!--  comment  -->",
  "po ime, RGB rgb(0-255,0-255,0-255), HEX #(rrggbb), HSL",
  "<ol><li></li>...<li></li></ol>",
  "<ul><li></li>...<li></li></ul>",
  "<div>",
];

// Function to generate random number
let rnd;
function randomNumber(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
let showBtns = function () {
  btn2.style.display = "none";
  btn1.style.display = "none";
  yes.style.display = "block";
  no.style.display = "block";
};
let hideButtons = function () {
  btn2.style.display = "block";
  btn1.style.display = "block";
  yes.style.display = "none";
  no.style.display = "none";
};
let init = function () {
  rnd = randomNumber(0, len - 1);
  console.log(rnd);

  lang.textContent = "Prasanje";
  word.textContent = htmlQuestions[rnd];
  panel.style.backgroundColor = "#4c6ef5";
  panel.style.color = "white";
  hideButtons();
};
let showMak = function () {
  wordCount.textContent = Number(wordCount.textContent) + 1;
  lang.textContent = "Odgovor";
  word.textContent = htmlAnswers[rnd];
  panel.style.backgroundColor = "white";
  panel.style.color = "#4c6ef5";
  headerText.textContent = "ODGOVOR";
  showBtns();
};
let newWord = function () {
  let score = Number(scoreEl.textContent);
  scoreEl.textContent = score + 1;

  init();
};
let reset = function () {
  scoreEl.textContent = 0;
  wordCount.textContent = 0;
  init();
};
const len = htmlQuestions.length;
const lang = document.querySelector(".lang");
const word = document.querySelector(".word");
const check = document.querySelector(".btn1");
const yes = document.querySelector(".yes");
const no = document.querySelector(".no");
const btn1 = document.querySelector(".btn1");
const btn2 = document.querySelector(".btn2");
const panel = document.querySelector(".panel");
const scoreEl = document.querySelector(".score-count");
const wordCount = document.querySelector(".word-count");
const headerText = document.querySelector(".header-text");
init();
check.addEventListener("click", showMak);
yes.addEventListener("click", newWord);
no.addEventListener("click", init);
btn2.addEventListener("click", reset);
